### ISSUE TITLE
After releasing pre-release version PR with same version is created

### ISSUE THREAD

**Issue by pstepniewskiconfigit** [google-github-actions/release-please-action#268]
After successfully releasing `5.0.0-beta.1`, release-please-action creates PR with with same version `5.0.0-beta.1` instead `5.0.0-beta.2` or just `5.0.0`.

#### Environment details
  - OS: windows-latest
  - Node.js version: 4.16.0
  - npm version: 7.6.0

**Comment by bcoe** [comment]
@pstepniewskiconfigit I don't believe that release-please's bumping logic currently understands pre-releases. Could you share the repository where this happened to you?

**Comment by pstepniewskiconfigit** [comment]
@bcoe Unfortunately, I can not. It is the organization's private repository.

**Comment by Coobaha** [comment]
https://github.com/Coobaha/suomea/pull/6 @bcoe Please check this repo, I have similar issue not sure what exactly causes it. According to logs (maybe verbose mode exists?) - it resolves to correct previous SHA but amount of changes is not.

**Comment by bcoe** [comment]
@Coobaha the problem appears to be when you "Rebase and Merge" a commit, rather than using "Squash and Merge", the tag points to your merge PR, rather than the actual commit with the release, however when you use the GitHub API to iterate over commits, the merge PR is not included in the set of commits:

```
chore: release 0.1.1 0b073a488725fd505b09fab2a9afb69759ecb012
fix: rename plugin to AnkiFinnish ea7cd8be331f4c29a84c2d3aeafca8491f2c2759
chore: release 0.1.0 4f8d7414b54b6ece376f4d4cdcc5dac45b807125
fix: testing release 28706239cd5f479fdbfc042ee24b509c2b50bc15
chore: initial commit 83e05aea96c87ef332e6d521599d616830d6f986
```

If you change the last release to point at `0b073a488725fd505b09fab2a9afb69759ecb012`, and use `Squash and Merge` for release PRs, it should correct the issue for you going forward.

**Comment by Coobaha** [comment]
🤔  I think i messed this with force-pushes during very first setup commits (and was/is using normal Merge mode in GH) Thanks for pointing out the root cause!
PS Would be nice if action would warn about such hiccups, not sure if there is a reliable way  of detecting it without false-positives

**Comment by bcoe** [comment]
@Coobaha will think about this as we improve our docs 👍
