### ISSUE TITLE
Document how to undo/recreate release

### ISSUE THREAD

**Issue by rsenden** [google-github-actions/release-please-action#272]
Is it possible to undo a release, and if so, can you please document how to do this? 

If for any reason there is an error in a release that makes it unusable, I think it would make sense to have the ability to roll back/undo that release, fix the error, and then release again with the same version number.

See for example https://github.com/fortify-ps/fortify-ssc-parser-symfony-security-checker/releases, where v1.0.1 is immediately superseded by v1.0.2 to fix an error in the build process; it would have been nicer to just re-publish a v1.0.1 release.

Somewhat related; suppose that someone accidentally deletes a release from the GitHub Releases page; is it possible to have release-please-action recreate that release instead of having to manually recreate it?

**Comment by kettanaito** [comment]
I don't think this tool supports reverting releases. Unfortunately, just as many other release automation tools, release-please tags, commits, and pushes the release changes to remote _before_ it can ensure that the release has actually succeeded (i.e. build artifacts were pushed somewhere). I think for now you'd have to do:

1. Manually delete the release tag so that release-please knows it's not the latest release.
2. Clean up your manifests (i.e. `package.json` in JavaScript) to refer to the previous version.
3. Delete any other release artifacts like generated GitHub releases and the release-please's manifest.

And then re-run the release manually. Even with this last but I'm not sure how to do that without going through the entire "change -> release pr -> release job on main" workflow.
