### ISSUE TITLE
Error: API rate limit exceeded for installation ID xx

### ISSUE THREAD

**Issue by bharathkkb** [google-github-actions/release-please-action#311]
I was testing out a release config today and possibly due to some misconfig on my part I ended up with 
https://github.com/bharathkkb/mono-bp-test/runs/2661822325?check_suite_focus=true

Then subsequent runs showed as passed but actually didn't
https://github.com/bharathkkb/mono-bp-test/runs/2661860431?check_suite_focus=true

[Some searching ](https://github.com/github/codeql/issues/5106)seems to imply this is coming from GH possibly due to release-please querying something however this means I have to wait ( ~1 hr) to continue testing. It would be great if 

- we could fail after a reasonable number of API calls or allow user configurability 
- show status correctly in subsequent runs

**Comment by rabraghib** [comment]
the error was just cause you didnt specify `bootstrap-sha` in your `release-please-config.json` file.

**Comment by junaidbinfarooq** [comment]
We recently set up this action and were faced with this issue right from the start. While searching for this, I came to know that I may need to add `bootstrap-sha` considering the fact that we have an existing codebase and not a new one. So I added a `.release-please-manifest.json` with the following info:
```JSON
{
  ".": "1.1.1",
  "bootstrap-sha": "last_release_commit_id"
}
```
But the error doesn't go away.
Moreover, while adding the action to our workflow, we used the default template for the workflow shown in the *action* documentation and added the following options under `with`:
```
release-type: php
package-name: our_package_name
```
What could we be doing wrong?
Besides, we are not sure what is this _installation id_?

**Comment by live627** [comment]
Same here. I want to use the `manifest`command for my PHP projects but when testing I noticed that the manifest command combined with the  `php` release type hangs for several minutes until the API limit is spent. using `node` worked as expected [because it is documented](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#manifest-driven-release-please). is that document updated @bcoe?

What determinees the calls? One call for each commit made since the last tag?

@junaidbinfarooq I think the installatin ID is a unique repo number.

**Comment by dkarter** [comment]
I have encountered this issue as well with a `simple` release type. 
It worked the first time I added release-please to my ci file (PR created), but it had the wrong version so I closed the PR, updated my tags and tried again. Since then it is no longer working and giving the same API call limit error.

https://github.com/dkarter/dotfiles/runs/6549556709?check_suite_focus=true

Adding the manifest file did not help

**Comment by achamas-playco** [comment]
I had this problem when adding the action to an existing repo with a Node setup, whereas when I previously tested on a fresh repo with the workflow included from the start it worked fine. You need to get the bootstrapping setup right.

To fix it, I removed the `.yml` workflow file and essentially stripped the repo of any release-please content (any `*release-please*` configs if you'd been trying to get them working like I did).

I then created a `release-please-config.json` file in the repo root with:

```json
{
  "bootstrap-sha": "<THE_BOOTSTRAP_SHA>",
  "release-type": "node",
  "packages": {
    ".": {}
  }
}
```

__Note the `bootstrap-sha` must be a full SHA.__

I also added the`.release-please-manifest.json` file in the root starting from the version I wanted `2.0.0` with:

```json
{ ".": "2.0.0" }
```

I then copied the workflow example from the [documentation](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#using-with-github-actions-and-lerna) and kept just the release part (good to know you could add deploy or publish after that with `if: ${{ steps.release.outputs.releases_created }}`).

```yml
on:
  push:
    branches:
      - main
name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
```

I then created a branch with those changes, and raised a PR to merge that back into the target branch `main`. The error stopped happening and my releases were created.

Hope that helps.

**Comment by ddennis** [comment]
I am also experiencing this issues - even after adding a 

`"bootstrap-sha": "8ec612df76d**************66604770"`

Any pointers on what to look for ?

**Comment by asaff1** [comment]
I can say I'm facing the same problem with release type "python".
![image](https://user-images.githubusercontent.com/18662769/200536612-b027e6a9-9358-4492-a9c6-f1b26cd20dd1.png)
Can someone explain, what types of API calls release please action do?

**Comment by tiplu-alexpovel** [comment]
We're having similar issues. Does a checkout help before running release-please? In the source, I can see it's mostly (entirely?) querying the GitHub API, even for things easily (and much faster) resolvable offline, like searching for merge commits.

Does it fall back to local `git` if it finds a `.git` directory? The docs use, if at all, `actions/checkout` *after* the release-please step.

**Comment by tiplu-alexpovel** [comment]
I'm also not sure how much bootstrapping can help in an established repo. We've been using release-please for a while now, and have created circa a couple dozen releases already. We have hundreds of version tags which release-please all investigates. If we could ignore most of these (most originate from before adopting release-please), it'd probably greatly help in reducing the number of API calls. *However*, [in the docs](https://github.com/googleapis/release-please/blob/9c94e0c2434e3a9bf01de64a6c39197a6955b83e/docs/manifest-releaser.md#bootstrapping) on bootstrapping, it says:

> Note: once a release-please generated PR has been merged, this config value will be ignored for all subsequent runs and can be removed.

So bootstrapping to limit API calls and time taken (even if it didn't exhaust API limits the release-please job takes about 90s for us) seems a non-starter for already-established repositories. I tested and confirmed this as well; speciyfing a `bootstrap-sha` of circa a month ago didn't stop the tool from querying all previous releases either.

As far as I can see, the tool even issues API requests for queries like "all merge commits", which could be much easier and faster (disk vs network) via local `git` calls.

**Comment by mateuszgazdziak** [comment]
Could we reopen this ticket? I also experience this issue.

**Comment by medz** [comment]
The problem is still! Today, March 15, 2023, two months have passed since the request to reopen it.

**Comment by Silverlan** [comment]
Can confirm that this is still a problem.

**Comment by felipefialho** [comment]
I'm still experiencing the same problem as well

**Comment by RyanMulready** [comment]
Hey It's June! Just hit this issue. This is not a new repo and release please has been working fine for months now. We triggered it when merging a decent amount of PRs in quick succession (~6ish).

**Comment by anthonwellsjo** [comment]
> Hey It's June! Just hit this issue. This is not a new repo and release please has been working fine for months now. We triggered it when merging a decent amount of PRs in quick succession (~6ish).

Almost identical story here...

**Comment by raja-anbazhagan** [comment]
happening right now. for me.

**Comment by nestor-sk** [comment]
Seeing the same problem. It would make sense to offer the option to use a checkout instead of the API to gather all the data that can be found in the git and only use the API for what is required from Github

**Comment by zzswang** [comment]
same issue

**Comment by huvber** [comment]
I'm experiencing it too

**Comment by fwuensche** [comment]
I've just faced the same issue while trying to setup release-please on my repository for the first time. 

### Issue

I already had a workflow setup, as below, and the failure happened while running the GitHub Action.

```
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: cherrypush
```

My error messages looked the same as the message shared on this thread. 

![image](https://github.com/google-github-actions/release-please-action/assets/1740848/c9f42c83-d30b-4c11-9d02-83f258f3b244)

### Solution

I've generated a new GitHub token here: https://github.com/settings/tokens

And made sure to provide **repo write** access, so I can use the token to create PRs.

![image](https://github.com/google-github-actions/release-please-action/assets/1740848/69f15851-a021-43f6-8d8d-832797378a64)

Then I installed release-please CLI: 

```
npm i release-please -g                                                  
```

And bootstraped it with: 

```
release-please bootstrap \
  --token=$GITHUB_TOKEN \
  --repo-url=cherrypush/cherry-cli \
  --release-type=node \
  --initial-version=1.2.2
```

Note that I had to set a initial version because my package was already at version 1.2.2. That might not be the case for you.

The command above generated a pull request: https://github.com/cherrypush/cherry-cli/pull/21

I merged the pull request, and the workflow did its job, generating a new PR with the change logs:
- https://github.com/cherrypush/cherry-cli/pull/22

Feel free to navigate the repo and reuse whatever fits you. It's open-source and MIT License.

I'm not certain this is the same issue for everyone, but hope it's helpful information anyway 🤗
