### ISSUE TITLE
Action should be able to read url from context as default value

### ISSUE THREAD

**Issue by goatwu1993** [google-github-actions/release-please-action#508]
action.yml can have better default values by reading action context.

changelog-host: {{ github.server_url }}
github-api-url: {{ github.api_url }}
github-graphql-url: {{ github.graphql_url }}

This shall not effect github.com repos, but will make life easier on GitHub Enterprise.

Check https://docs.github.com/en/actions/learn-github-actions/contexts

**Comment by ZachHaber** [comment]
I was trying this out locally on an enterprise server to reduce some config.
Currently, if you use `github-graphql-url: ${{ github.graphql_url }}` in the release-please.yml it will fail because it is expecting the url without the `/graphql` on the end, and I can only assume that it fails due to having `/graphql/graphql`.
There were also no real messages to give indication of what was going wrong. Just "Error: release-please failed: Not Found"

**Comment by goatwu1993** [comment]
Hmm. Maybe trim the url right after core.getInput ?

**Comment by goatwu1993** [comment]
@ZachHaber 
I test on my site and found something similar
github-api-url: https://example.github.com/api/v3 => https://example.github.com/api/v3 (Nothing changed)
github-graphql-url: https://example.github.com/api => https://example.github.com/api/graphql (an extra **/graphql** )

**Comment by goatwu1993** [comment]
Hmm I tried the workaround

`javascript
graphqlUrl: core.getInput('github-graphql-url').replace(/\/graphql$/, '') || GITHUB_GRAPHQL_URL,
`

And worked.
